import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface ResumeExperience {
  title: string;
  company: string;
  period: string;
  highlights: string[];
}

interface ResumeEducation {
  degree: string;
  school: string;
  year: string;
}

interface ResumeData {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  summary: string;
  skills: string[];
  experience: ResumeExperience[];
  education: ResumeEducation[];
}

interface Recommendation {
  title: string;
  description: string;
  impact: string;
}

interface AnalysisData {
  overallScore: number;
  atsScore: number;
  keywordScore: number;
  strengths: string[];
  weaknesses: string[];
  recommendations: Recommendation[];
  existingSkills: string[];
  skillsToDevelop: string[];
}

interface JobMatchData {
  matchScore: number;
  foundSkills: string[];
  missingSkills: string[];
  aiSuggestions: string[];
}

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;

const MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const COLORS = {
  primary: [37, 99, 235] as [number, number, number],
  dark: [31, 41, 55] as [number, number, number],
  muted: [107, 114, 128] as [number, number, number],
  light: [243, 244, 246] as [number, number, number],
  success: [22, 163, 74] as [number, number, number],
  warning: [217, 119, 6] as [number, number, number],
  danger: [220, 38, 38] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

function sanitizeText(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }

  return String(value)
    .replace(/[^\x20-\x7E\n\r\t]/g, "")
    .trim();
}

function getScoreColor(score: number): [number, number, number] {
  if (score >= 90) return COLORS.success;
  if (score >= 70) return COLORS.warning;
  return COLORS.danger;
}

function addPageHeader(doc: jsPDF, resumeName: string) {
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, PAGE_WIDTH, 7, "F");

  doc.setTextColor(...COLORS.dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);

  doc.text("Resume Analysis Report", MARGIN, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);

  doc.text(
    sanitizeText(resumeName),
    MARGIN,
    29
  );

  doc.setDrawColor(220, 220, 220);
  doc.line(
    MARGIN,
    34,
    PAGE_WIDTH - MARGIN,
    34
  );
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();

  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);

    doc.setDrawColor(230, 230, 230);
    doc.line(
      MARGIN,
      PAGE_HEIGHT - 15,
      PAGE_WIDTH - MARGIN,
      PAGE_HEIGHT - 15
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);

    doc.text(
      "Generated by Resume Analyzer",
      MARGIN,
      PAGE_HEIGHT - 9
    );

    doc.text(
      `Page ${page} of ${pageCount}`,
      PAGE_WIDTH - MARGIN,
      PAGE_HEIGHT - 9,
      { align: "right" }
    );
  }
}

function addSectionTitle(
  doc: jsPDF,
  title: string,
  y: number
): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.dark);

  doc.text(title, MARGIN, y);

  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.8);

  doc.line(
    MARGIN,
    y + 3,
    MARGIN + 18,
    y + 3
  );

  return y + 11;
}

function ensureSpace(
  doc: jsPDF,
  y: number,
  requiredHeight: number,
  resumeName: string
): number {
  if (y + requiredHeight > PAGE_HEIGHT - 25) {
    doc.addPage();
    addPageHeader(doc, resumeName);
    return 45;
  }

  return y;
}

function addScoreCard(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  title: string,
  score: number
) {
  const height = 30;

  doc.setFillColor(...COLORS.light);
  doc.roundedRect(x, y, width, height, 3, 3, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);

  doc.text(title, x + width / 2, y + 9, {
    align: "center",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(...getScoreColor(score));

  doc.text(`${score}%`, x + width / 2, y + 23, {
    align: "center",
  });
}

function addBulletList(
  doc: jsPDF,
  items: string[],
  y: number,
  resumeName: string
): number {
  let currentY = y;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.dark);

  for (const item of items) {
    const text = sanitizeText(item);

    if (!text) continue;

    const lines = doc.splitTextToSize(
      text,
      CONTENT_WIDTH - 8
    );

    currentY = ensureSpace(
      doc,
      currentY,
      lines.length * 4.5 + 5,
      resumeName
    );

    doc.setFillColor(...COLORS.primary);
    doc.circle(MARGIN + 1.5, currentY - 1.3, 1, "F");

    doc.text(
      lines,
      MARGIN + 6,
      currentY
    );

    currentY += lines.length * 4.5 + 3;
  }

  return currentY;
}

export function generateResumeAnalysisPdf(
  resume: ResumeData,
  analysis: AnalysisData,
  jobMatch?: JobMatchData
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const resumeName =
    sanitizeText(resume.fullName) || "Resume";

  addPageHeader(doc, resumeName);

  let y = 43;

  // --------------------------------------------------
  // Candidate Information
  // --------------------------------------------------

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.dark);

  doc.text(resumeName, MARGIN, y);

  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.muted);

  const contactInfo = [
    resume.email,
    resume.phone,
    resume.location,
  ]
    .filter(Boolean)
    .map(sanitizeText)
    .join("  |  ");

  if (contactInfo) {
    const contactLines = doc.splitTextToSize(
      contactInfo,
      CONTENT_WIDTH
    );

    doc.text(contactLines, MARGIN, y);
    y += contactLines.length * 4.5 + 5;
  } else {
    y += 5;
  }

  // --------------------------------------------------
  // Score Summary
  // --------------------------------------------------

  y = addSectionTitle(
    doc,
    "Analysis Summary",
    y
  );

  const scoreGap = 4;
  const scoreWidth =
    (CONTENT_WIDTH - scoreGap * 2) / 3;

  addScoreCard(
    doc,
    MARGIN,
    y,
    scoreWidth,
    "Overall Score",
    analysis.overallScore
  );

  addScoreCard(
    doc,
    MARGIN + scoreWidth + scoreGap,
    y,
    scoreWidth,
    "ATS Score",
    analysis.atsScore
  );

  addScoreCard(
    doc,
    MARGIN + (scoreWidth + scoreGap) * 2,
    y,
    scoreWidth,
    "Keyword Score",
    analysis.keywordScore
  );

  y += 42;

  // --------------------------------------------------
  // Resume Summary
  // --------------------------------------------------

  if (resume.summary) {
    y = addSectionTitle(
      doc,
      "Professional Summary",
      y
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.dark);

    const summaryLines = doc.splitTextToSize(
      sanitizeText(resume.summary),
      CONTENT_WIDTH
    );

    y = ensureSpace(
      doc,
      y,
      summaryLines.length * 4.5 + 5,
      resumeName
    );

    doc.text(summaryLines, MARGIN, y);

    y += summaryLines.length * 4.5 + 8;
  }

  // --------------------------------------------------
  // Strengths
  // --------------------------------------------------

  if (analysis.strengths?.length) {
    y = ensureSpace(doc, y, 25, resumeName);

    y = addSectionTitle(
      doc,
      "Strengths",
      y
    );

    y = addBulletList(
      doc,
      analysis.strengths,
      y,
      resumeName
    );

    y += 3;
  }

  // --------------------------------------------------
  // Weaknesses
  // --------------------------------------------------

  if (analysis.weaknesses?.length) {
    y = ensureSpace(doc, y, 25, resumeName);

    y = addSectionTitle(
      doc,
      "Areas for Improvement",
      y
    );

    y = addBulletList(
      doc,
      analysis.weaknesses,
      y,
      resumeName
    );

    y += 3;
  }

  // --------------------------------------------------
  // Skills
  // --------------------------------------------------

  if (
    analysis.existingSkills?.length ||
    analysis.skillsToDevelop?.length
  ) {
    y = ensureSpace(doc, y, 30, resumeName);

    y = addSectionTitle(
      doc,
      "Skills",
      y
    );

    autoTable(doc, {
      startY: y,
      margin: {
        left: MARGIN,
        right: MARGIN,
      },
      head: [["Existing Skills", "Skills to Develop"]],
      body: [
        [
          analysis.existingSkills
            .map(sanitizeText)
            .join(", "),
          analysis.skillsToDevelop
            .map(sanitizeText)
            .join(", "),
        ],
      ],
      theme: "grid",
      styles: {
        font: "helvetica",
        fontSize: 8,
        cellPadding: 4,
        textColor: COLORS.dark,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontStyle: "bold",
      },
      columnStyles: {
        0: {
          cellWidth: CONTENT_WIDTH / 2,
        },
        1: {
          cellWidth: CONTENT_WIDTH / 2,
        },
      },
    });

    y =
      (doc as jsPDF & {
        lastAutoTable?: { finalY: number };
      }).lastAutoTable?.finalY ?? y + 30;

    y += 10;
  }

  // --------------------------------------------------
  // Recommendations
  // --------------------------------------------------

  if (analysis.recommendations?.length) {
    y = ensureSpace(doc, y, 30, resumeName);

    y = addSectionTitle(
      doc,
      "AI Recommendations",
      y
    );

    const recommendationRows =
      analysis.recommendations.map((recommendation) => [
        sanitizeText(recommendation.title),
        sanitizeText(recommendation.description),
        sanitizeText(recommendation.impact),
      ]);

    autoTable(doc, {
      startY: y,
      margin: {
        left: MARGIN,
        right: MARGIN,
      },
      head: [["Recommendation", "Description", "Impact"]],
      body: recommendationRows,
      theme: "grid",
      styles: {
        font: "helvetica",
        fontSize: 8,
        cellPadding: 3.5,
        textColor: COLORS.dark,
        overflow: "linebreak",
        valign: "top",
      },
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontStyle: "bold",
      },
      columnStyles: {
        0: {
          cellWidth: 42,
        },
        1: {
          cellWidth: 105,
        },
        2: {
          cellWidth: 23,
          halign: "center",
        },
      },
    });

    y =
      (doc as jsPDF & {
        lastAutoTable?: { finalY: number };
      }).lastAutoTable?.finalY ?? y + 40;

    y += 10;
  }

  // --------------------------------------------------
  // Experience
  // --------------------------------------------------

  if (resume.experience?.length) {
    y = ensureSpace(doc, y, 30, resumeName);

    y = addSectionTitle(
      doc,
      "Experience",
      y
    );

    for (const experience of resume.experience) {
      y = ensureSpace(doc, y, 25, resumeName);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(...COLORS.dark);

      doc.text(
        sanitizeText(experience.title),
        MARGIN,
        y
      );

      y += 4.5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.muted);

      doc.text(
        `${sanitizeText(experience.company)} | ${sanitizeText(
          experience.period
        )}`,
        MARGIN,
        y
      );

      y += 6;

      y = addBulletList(
        doc,
        experience.highlights,
        y,
        resumeName
      );

      y += 3;
    }
  }

  // --------------------------------------------------
  // Education
  // --------------------------------------------------

  if (resume.education?.length) {
    y = ensureSpace(doc, y, 30, resumeName);

    y = addSectionTitle(
      doc,
      "Education",
      y
    );

    for (const education of resume.education) {
      y = ensureSpace(doc, y, 15, resumeName);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.dark);

      doc.text(
        sanitizeText(education.degree),
        MARGIN,
        y
      );

      y += 4.5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.muted);

      doc.text(
        `${sanitizeText(education.school)} | ${sanitizeText(
          education.year
        )}`,
        MARGIN,
        y
      );

      y += 8;
    }
  }

  // --------------------------------------------------
  // Job Match
  // --------------------------------------------------

  if (jobMatch) {
    doc.addPage();

    addPageHeader(
      doc,
      `${resumeName} - Job Match`
    );

    y = 45;

    y = addSectionTitle(
      doc,
      "Job Match Analysis",
      y
    );

    addScoreCard(
      doc,
      MARGIN,
      y,
      55,
      "Match Score",
      jobMatch.matchScore
    );

    y += 42;

    if (jobMatch.foundSkills?.length) {
      y = addSectionTitle(
        doc,
        "Found Skills",
        y
      );

      y = addBulletList(
        doc,
        jobMatch.foundSkills,
        y,
        resumeName
      );

      y += 4;
    }

    if (jobMatch.missingSkills?.length) {
      y = ensureSpace(doc, y, 25, resumeName);

      y = addSectionTitle(
        doc,
        "Missing Skills",
        y
      );

      y = addBulletList(
        doc,
        jobMatch.missingSkills,
        y,
        resumeName
      );

      y += 4;
    }

    if (jobMatch.aiSuggestions?.length) {
      y = ensureSpace(doc, y, 25, resumeName);

      y = addSectionTitle(
        doc,
        "AI Suggestions for This Job",
        y
      );

      y = addBulletList(
        doc,
        jobMatch.aiSuggestions,
        y,
        resumeName
      );
    }
  }

  // --------------------------------------------------
  // Footer
  // --------------------------------------------------

  addFooter(doc);

  // --------------------------------------------------
  // Download
  // --------------------------------------------------

  const safeName =
    resumeName
      .replace(/[^a-zA-Z0-9-_ ]/g, "")
      .trim()
      .replace(/\s+/g, "-") || "Resume";

  const filename = `${safeName}-Resume-Analysis.pdf`;

  doc.save(filename);
}